#!/usr/bin/env bun
/**
 * generate-icons.ts — vendor the glyph subset the dashboard actually uses.
 *
 * Reads SVG assets from `@phosphor-icons/core` (a bundled dependency, MIT) and
 * emits `docs/js/ds/icon-paths.ts` containing just their path data. Committing
 * the generated file means the browser needs no icon font, no CDN and no build
 * step, while the glyphs stay regenerable instead of hand-copied.
 *
 * Run after adding a glyph to MANIFEST:
 *   bun run scripts/dashboard/ds/generate-icons.ts
 *
 * Output is a single JSON object, so `{ ok, data, error }` reporting stays
 * consistent with the rest of scripts/.
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const REPO_ROOT = resolve(import.meta.dir, "..", "..", "..");
const ASSETS = join(
  REPO_ROOT,
  "node_modules",
  "@phosphor-icons",
  "core",
  "assets",
);
const OUT = join(REPO_ROOT, "docs", "js", "ds", "icon-paths.ts");

/**
 * Glyphs the dashboard uses, by weight. A `-fill` suffix selects the filled
 * weight; everything else is Phosphor "regular".
 */
export const MANIFEST = [
  // shell + nav destinations
  "hammer",
  "gauge",
  "list-checks",
  "stack",
  "flow-arrow",
  "terminal-window",
  "sparkle",
  "plus-circle",
  "chart-line",
  "books",
  "file-text",
  "users-three",
  // actions
  "arrows-clockwise",
  "magnifying-glass",
  "copy",
  "x",
  "caret-down",
  "caret-right",
  "funnel",
  "code",
  "list-bullets",
  "git-branch",
  "git-pull-request",
  "scales",
  // status + issue types
  "check-circle-fill",
  "circle",
  "circle-half",
  "warning-circle",
  "check-square",
  "bug",
  "broom",
] as const;

/** Absolute path to a glyph's SVG, resolving the `-fill` weight suffix. */
export function assetPathFor(
  name: string,
  assetsRoot: string = ASSETS,
): string {
  return name.endsWith("-fill")
    ? join(assetsRoot, "fill", `${name}.svg`)
    : join(assetsRoot, "regular", `${name}.svg`);
}

/** The `d` attribute of the single path in a Phosphor SVG. */
export function pathDataFrom(svg: string): string | null {
  const paths = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map(
    (m) => m[1] as string,
  );
  if (paths.length !== 1) return null;
  return paths[0] ?? null;
}

function main(): void {
  const entries: [string, string][] = [];
  const missing: string[] = [];

  for (const name of MANIFEST) {
    const file = assetPathFor(name);
    if (!existsSync(file)) {
      missing.push(name);
      continue;
    }
    const d = pathDataFrom(readFileSync(file, "utf8"));
    if (d === null) {
      missing.push(`${name} (unexpected multi-path svg)`);
      continue;
    }
    entries.push([name, d]);
  }

  if (missing.length > 0) {
    console.log(
      JSON.stringify({
        ok: false,
        data: null,
        error: `Glyphs unavailable in @phosphor-icons/core: ${missing.join(", ")}`,
      }),
    );
    process.exit(1);
  }

  const body = entries
    .map(([name, d]) => `  ${JSON.stringify(name)}: ${JSON.stringify(d)},`)
    .join("\n");

  writeFileSync(
    OUT,
    `// Generated by scripts/dashboard/ds/generate-icons.ts — do not edit by hand.
// Source: @phosphor-icons/core (MIT). Add a glyph to that script's MANIFEST and
// re-run it rather than pasting path data here.

export const ICON_PATHS = {
${body}
} as const;

export type IconName = keyof typeof ICON_PATHS;
`,
  );

  console.log(
    JSON.stringify({
      ok: true,
      data: { glyphs: entries.length, out: "docs/js/ds/icon-paths.ts" },
      error: null,
    }),
  );
}

if (import.meta.main) main();
